Repository nielsmaerten/gluco-check, pull requests merged in 2021-05, with the labels that each got.

#116 feature/language-selector add ability to manually switch language to frontend
  gluco-check-frontend/package.json
  gluco-check-frontend/public/locales/en/translation.json
  gluco-check-frontend/public/locales/nl/translation.json
  gluco-check-frontend/src/App.test.tsx
  gluco-check-frontend/src/App.tsx
  gluco-check-frontend/src/__snapshots__/App.test.tsx.snap
  gluco-check-frontend/src/components/LanguageSelector.test.tsx
  gluco-check-frontend/src/components/LanguageSelector.tsx
  gluco-check-frontend/src/components/SettingsForm.test.tsx
  gluco-check-frontend/src/components/SettingsForm.tsx
  gluco-check-frontend/src/components/__snapshots__/LanguageSelector.test.tsx.snap
  gluco-check-frontend/src/components/__snapshots__/SettingsForm.test.tsx.snap
  gluco-check-frontend/src/lib/constants.ts
  gluco-check-frontend/src/lib/enums.ts
  gluco-check-frontend/src/lib/i18n.ts
  gluco-check-frontend/src/lib/navigation.test.ts
  gluco-check-frontend/src/lib/navigation.ts
  gluco-check-frontend/src/pages/Landing.test.tsx
  gluco-check-frontend/src/pages/Landing.tsx
  gluco-check-frontend/src/pages/Welcome.test.tsx
  gluco-check-frontend/src/pages/Welcome.tsx
  gluco-check-frontend/src/pages/__snapshots__/Welcome.test.tsx.snap
  yarn.lock
Labels: front-end

#123 fix: Sensor was inserted NaN years ago
  .github/workflows/test-build-deploy.yml
  gluco-check-core/src/main/clients/nightscout/NightscoutClient.ts
  gluco-check-core/src/main/clients/nightscout/queries/CannulaAge.ts
  gluco-check-core/src/main/clients/nightscout/queries/CarbsInsulinOnBoard.ts
  gluco-check-core/src/main/clients/nightscout/queries/PumpStatus.ts
  gluco-check-core/src/main/clients/nightscout/queries/SensorAge.ts
  gluco-check-core/src/main/i18n/humanizers/BloodSugar.ts
  gluco-check-core/src/main/i18n/humanizers/CannulaAge.ts
  gluco-check-core/src/main/i18n/humanizers/CarbsOnBoard.ts
  gluco-check-core/src/main/i18n/humanizers/InsulinOnBoard.ts
  gluco-check-core/src/main/i18n/humanizers/PumpBattery.ts
  gluco-check-core/src/main/i18n/humanizers/PumpReservoir.ts
  gluco-check-core/src/main/i18n/humanizers/SensorAge.ts
  gluco-check-core/test/fakes/objects/fakeDmQuery.ts
  gluco-check-core/test/specs/main/core/Humanizers.spec.ts
Labels: back-end, bug

#126 fix: Carbs on Board are 'not found' if zero
  gluco-check-core/src/main/i18n/humanizers/CarbsOnBoard.ts
  gluco-check-core/src/main/i18n/humanizers/InsulinOnBoard.ts
  gluco-check-core/src/main/i18n/humanizers/PumpBattery.ts
  gluco-check-core/src/main/i18n/humanizers/PumpReservoir.ts
Labels: back-end, bug

#121 Update Action definition to support Dutch
  gluco-check-action/.env.example
  gluco-check-action/README.md
  gluco-check-action/definitions/custom/intents/nl/READ_METRICS.yaml
  gluco-check-action/definitions/custom/types/nl/DmMetric.yaml
  gluco-check-action/definitions/settings/nl/settings.yaml
  gluco-check-common/strings/en-US/assistant-action.md
Labels: translation

#132 fix: Automated fix for #130
  gluco-check-webhooks/src/fix-units/index.ts
  gluco-check-webhooks/src/index.ts
Labels: back-end, bug
